version: "3.9"
services:
  database:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  
  identity:
    build:
      context: .
      dockerfile: identity/Klinker.Home.Identity.Web/Dockerfile
    ports:
      - "5166:80"
    depends_on:
      - database